packages:
    - package:
        name: javax.servlet.ServletRequest
        file: ServletRequest.java
        type: interface
        methods:
            - method:
                name: getAttribute
                type: source
            - method:
                name: getAttributeNames
                type: source
            - method:
                name: getCharacterEncoding
                type: source
            - method:
                name: getContentType
                type: source
            - method:
                name: getParameter
                type: source
            - method:
                name: getParameterNames
                type: source
            - method:
                name: getParameterValues
                type: source
            - method:
                name: getParameterMap
                type: source
            - method:
                name: getProtocol
                type: source
            - method:
                name: getScheme
                type: source              
            - method:
                name: getServerName
                type: source
            - method:
                name: getRemoteAddr
                type: source
            - method:
                name: getRemoteHost
                type: source
            - method:
                name: getLocalName
                type: source
            - method:
                name: getLocalAddr
                type: source
            - method:
                name: getLocalAddr
                type: source

    - package:
        name: javax.servlet.http.HttpServletRequest
        file: HttpServletRequest.java
        type: interface
        methods:
            - method:
                name: getAuthType
                type: source
            - method:
                name: getHeader
                type: source
            - method:
                name: getHeaders
                type: source
            - method:
                name: getMethod
                type: source
            - method:
                name: getPathInfo
                type: source
            - method:
                name: getPathTranslated
                type: source
            - method:
                name: getContextPath
                type: source
            - method:
                name: getQueryString
                type: source
            - method:
                name: getRemoteUser
                type: source
            - method:
                name: getRequestedSessionId
                type: source
            - method:
                name: getRequestURI
                type: source
            - method:
                name: getRequestURL
                type: source
            - method:
                name: getServletPath
                type: source
    - package:
        name: javax.servlet.http.Cookie
        file: Cookie.java
        type: class
        methods:
            - method:
                name: getComment
                type: source
            - method:
                name: getDomain
                type: source
            - method:
                name: getPath
                type: source
            - method:
                name: getName
                type: source
            - method:
                name: getValue
                type: source
    - package:
        name: javax.servlet.ServletConfig
        file: ServletConfig.java
        type: interface
        methods:
            - method:
                name: getInitParameter
                type: source
            - method:
                name: getInitParameterNames
                type: source
    - package:
        name: javax.servlet.GenericServlet
        file: GenericServlet.java
        type: abstract
        methods:
            - method:
                name: getInitParameter
                type: source
            - method:
                name: getInitParameterNames
                type: source
    - package:
        name: java.sql.ResultSet
        file: ResultSet.java
        type: interface
        methods:
            - method:
                name: getString
                type: source
            - method:
                name: getObject
                type: source
    - package:
        name: java.awt.TextComponent
        file: TextComponent.java
        type: class
        methods:
            - method:
                name: getSelectedText
                type: source
            - method:
                name: getText
                type: source
    - package:
        name: java.io.Console
        file: Console.java
        type: class
        methods:
            - method:
                name: readLine
                type: source
            - method:
                name: readPassword
                type: source
    - package:
        name: java.io.DataInputStream
        file: DataInputStream.java
        type: class
        methods:
            - method:
                name: readLine
                type: source
            - method:
                name: readUTF
                type: source
    - package:
        name: java.io.LineNumberReader
        file: LineNumberReader.java
        type: class
        methods:
            - method:
                name: readLine
                type: source
    - package:
        name: javax.servlet.http.HttpSession
        file: HttpSession.java
        type: interface
        methods:
            - method:
                name: getAttribute
                type: source
            - method:
                name: getAttributeNames
                type: source
            - method:
                name: getValue
                type: source
            - method:
                name: getValueNames
                type: source
    - package:
        name: java.lang.System
        file: System.java
        type: class
        methods:
            - method:
                name: getProperty
                type: source
            - method:
                name: getProperties
                type: source
            - method:
                name: getenv
                type: source
    - package:
        name: javax.servlet.ServletContext
        file: ServletContext.java
        type: interface
        methods:
            - method:
                name: getResourceAsStream
                type: source
            - method:
                name: getRealPath
                type: source
    - package:
        name: java.util.Properties
        file: Properties.java
        type: class
        methods:
            - method:
                name: getProperty
                type: source
    - package:
        name: java.lang.Class
        file: Class.java
        type: class
        methods:
            # - source:
            #     name: getResource
            - method:
                name: getResourceAsStream
                type: source
    - package:
        name: javax.xml.xpath.XPath
        file: XPath.java
        type: interface
        methods:
            - method:
                name: evaluate
                type: source
    - package:
        name: javax.xml.xpath.XPathExpression
        file: XPathExpression.java
        type: interface
        methods:
            - method:
                name: evaluate
                type: source
    - package:
        name: java.net.URLEncoder
        file: URLEncoder.java
        type: class
        methods:
            - method:
                name: encode
                type: sanitiser
    - package:
        name: java.net.URLDecoder
        file: URLDecoder.java
        type: class
        methods:
            - method:
                name: decode
                type: sanitiser
    - package:
        name: org.apache.commons.lang.StringEscapeUtils
        file: StringEscapeUtils.java
        type: class
        methods:
            - method:
                name: escapeJava
                type: sanitiser
            - method:
                name: unescapeJava
                type: sanitiser
            - method:
                name: escapeHtml
                type: sanitiser
            - method:
                name: unescapeHtml
                type: sanitiser
            - method:
                name: escapeXml
                type: sanitiser
            - method:
                name: unescapeXml
                type: sanitiser
            - method:
                name: escapeCsv
                type: sanitiser
            - method:
                name: unescapeCsv
                type: sanitiser
    - package:
        name: java.lang.Runtime
        file: Runtime.java
        type: class
        methods:
            - method:
                name: exec
                type: sink
    - package:
        name: java.lang.Thread
        file: Thread.java
        type: class
        methods:
            - method:
                name: sleep
                type: sink
    - package:
        name: java.lang.System
        file: System.java
        type: class
        methods:
            - method:
                name: load
                type: sink
            - method:
                name: loadLibrary
                type: sink
    - package:
        name: javax.servlet.http.Cookie
        file: Cookie.java
        type: class
        methods:
            - method:
                name: setComment
                type: sink
            - method:
                name: setDomain
                type: sink
            - method:
                name: setPath
                type: sink
            - method:
                name: setValue
                type: sink
    - package:
        name: java.io.PrintWriter
        file: PrintWriter.java
        type: class
        methods:
            - method:
                name: print
                type: sink
            - method:
                name: println
                type: sink
            - method:
                name: write
                type: sink
    - package:
        name: javax.servlet.ServletOutputStream
        file: PrintWriter.java
        type: abstract
        methods:
            - method:
                name: print
                type: sink
            - method:
                name: println
                type: sink
    - package:
        name: javax.servlet.jsp.JspWriter
        file: JspWriter.java
        type: abstract
        methods:
            - method:
                name: print
                type: sink
            - method:
                name: println
                type: sink
    - package:
        name: javax.servlet.ServletRequest
        file: ServletRequest.java
        type: interface
        methods:
            - method:
                name: setAttribute
                type: sink
            - method:
                name: setCharacterEncoding
                type: sink
    - package:
        name: javax.servlet.http.HttpServletResponse
        file: HttpServletResponse.java
        type: interface
        methods:
            - method:
                name: sendError
                type: sink
            - method:
                name: setDateHeader
                type: sink
            - method:
                name: addDateHeader
                type: sink
            - method:
                name: setHeader
                type: sink
            - method:
                name: addHeader
                type: sink
            - method:
                name: setIntHeader
                type: sink
            - method:
                name: addIntHeader
                type: sink
    - package:
        name: javax.servlet.ServletResponse
        file: ServletResponse.java
        type: interface
        methods:
            - method:
                name: setCharacterEncoding
                type: sink
            - method:
                name: setContentType
                type: sink
    - package:
        name: javax.servlet.http.HttpSession
        file: HttpSession.java
        type: interface
        methods:
            - method:
                name: setAttribute
                type: sink
            - method:
                name: putValue
                type: sink
    - package:
        name: javax.servlet.http.HttpServletResponse
        file: HttpServletResponse.java
        type: interface
        methods:
            - method:
                name: sendRedirect
                type: sink
    - package:
        name: javax.naming.directory.InitialDirContext
        file: InitialDirContext.java
        type: class
        methods:
            - method:
                name: InitialDirContext
                type: sink
            - method:
                name: search
                type: sink
    # - package:
    #     name: javax.naming.directory.SearchControls
    #     file: SearchControls.java
    #     type: class
    #     methods:
    #         - method:
    #             name: setReturningAttributes
    - package:
        name: java.io.PrintStream
        file: PrintStream.java
        type: class
        methods:
            - method:
                name: print
                type: sink
            - method:
                name: println
                type: sink
    - package:
        name: java.util.logging.Logger
        file: Logger.java
        type: class
        methods:
            - method:
                name: config
                type: sink
            - method:
                name: fine
                type: sink
            - method:
                name: finer
                type: sink
            - method:
                name: finest
                type: sink
            - method:
                name: info
                type: sink
            - method:
                name: warning
                type: sink
            - method:
                name: severe
                type: sink
            - method:
                name: entering
                type: sink
            - method:
                name: log
                type: sink
    - package:
        name: org.apache.commons.logging.Log
        file: Log.java
        type: interface
        methods:
            - method:
                name: debug
                type: sink
            - method:
                name: error
                type: sink
            - method:
                name: fatal
                type: sink
            - method:
                name: info
                type: sink
            - method:
                name: trace
                type: sink
            - method:
                name: warn
                type: sink
    - package:
        name: java.io.BufferedWriter
        file: BufferedWriter.java
        type: class
        url: https://docs.oracle.com/javase/8/docs/api/java/io/BufferedWriter.html
        methods:
            - method:
                name: write
                type: sink
    - package:
        name: javax.servlet.ServletContext
        file: ServletContext.java
        type: interface
        methods:
            - method:
                name: log
                type: sink
    - package:
        name: javax.servlet.GenericServlet
        file: GenericServlet.java
        type: abstract
        methods:
            - method:
                name: log
                type: sink
    - package:
        name: java.lang.Class
        file: Class.java
        type: class
        methods:
            - method:
                name: getResource
                type: sink
            - method:
                name: getResourceAsStream
                type: sink
    - package:
        name: javax.mail.internet.InternetAddress
        file: InternetAddress.java
        type: class
        methods:
            - method:
                name: InternetAddress
                type: sink
            - method:
                name: parse
                type: sink
    - package:
        name: java.lang.Class
        file: Class.java
        type: class
        methods:
            - method:
                name: forName
                type: sink
            - method:
                name: getField
                type: sink
            - method:
                name: getMethod
                type: sink
            - method:
                name: getDeclaredField
                type: sink
            - method:
                name: getDeclaredMethod
                type: sink
    - package:
        name: java.sql.DriverManager
        file: DriverManager.java
        type: class
        methods:
            - method:
                name: getConnection
                type: sink
    - package:
        name: java.sql.Connection
        file: Connection.java
        type: interface
        methods:
            - method:
                name: prepareStatement
                type: sink
            - method:
                name: prepareCall
                type: sink
    - package:
        name: javax.persistence.EntityManager
        file: EntityManager.java
        type: interface
        methods:
            - method:
                name: createNativeQuery
                type: sink
            - method:
                name: createQuery
                type: sink